### ISSUE TITLE
v-snip should not remove non-text content on CSS type

### ISSUE THREAD

**Issue by carbotaniuman** [ajobi/vue-snip#14]
![image](https://user-images.githubusercontent.com/41451839/123868710-ae6e8d80-d8f5-11eb-8913-ad2c8dc90587.png)

I wanted to make something like the above (this is with manually modified HTML). It appears that this is due to [this line](https://github.com/ajobi/vue-snip/blob/dacfe9ed053d7e3b51bd7af6a4a29dd86653ed13/src/method/method.css.js#L5), which seems like it is only needed for the JS method, and can probably be removed here?

**Comment by ajobi** [comment]
Thanks for posting the issue @carbotaniuman ! It actually cannot be removed here for one reason: The method is meant to be reactive and you are able to switch between methods freely. If you are switching from JS to CSS, the text in the HTML element needs to be restored fully as the JS method could have manipulated it. Would using JS method for this element solve the issue for you?

**Comment by carbotaniuman** [comment]
The JS element also.cuts off the image (the Japan flag there was manually added), so it wouldn't work for me. I'm not too familiar with how Vue directives and reactivity works, but would saving innerHtml be an option?

**Comment by ajobi** [comment]
@carbotaniuman the solution for your case might be what you see in the demo with floated + js options checked https://ajobi.github.io/vue-snip/. If you follow the HTML structure in the demo, you should be able to achieve your desired result. Let me know how it went 👍
