### ISSUE TITLE
Data is not updated

### ISSUE THREAD

**Issue by KingJardon** [ajobi/vue-snip#25]
I have updated the data, but it still shows the old data

**Comment by ajobi** [comment]
@KingJardon could you be more specific? A code snippet or a demo would be awesome.

**Comment by KingJardon** [comment]
`<p v-snip="{ lines: 2, mode: 'css', onSnipped }">
      {{ text }}
    </p>`

This text has changed，but view not updated
Let's say the initial value is 0，Whatever happens to the value，The view is always showing 0

**Comment by ajobi** [comment]
@KingJardon so you have changed the value of `text` and the old value stays displayed, is this what you are saying?

**Comment by KingJardon** [comment]
> @KingJardon so you have changed the value of `text` and the old value stays displayed, is this what you are saying?

Yes it is.

**Comment by ajobi** [comment]
Okay thanks! This sounds like a bug, I will look at it in the upcoming weeks.

**Comment by duvalale** [comment]
Just encountered the same bug, any progress made on a fix ? :)
thanks

**Comment by ajobi** [comment]
@duvalale not yet unfortunately, I am busy with other projects right now and will be for a couple more weeks.

**Comment by Maizerer** [comment]
Hi, I have the same issue. Any progress made on a fix ?

**Comment by ajobi** [comment]
Unfortunately, no, way too busy 😀

**Comment by revelstoke-tim** [comment]
@ajobi @KingJardon  @Maizerer @duvalale

The issue is that the directive implements the `updated` hook, which breaks it as there are now to snip() watchers on the same element.  Removing the `updated` hook fixes the issue.

**Comment by revelstoke-tim** [comment]
Please disregard my previous comment -- it only works intermittently using this method.  I've come up with a bit of a hack to workaround it, which I'll submit as a PR.  From what I can divine, there's something about js-snip which prevents Vue from updating a snipped element successfully.

**Comment by revelstoke-tim** [comment]
PR submitted.  https://github.com/ajobi/vue-snip/pull/31
