### ISSUE TITLE
Nuxt 3 compatibility

### ISSUE THREAD

**Issue by masterWeber** [ajobi/vue-snip#32]
I wrote a simple plugin for VueShip
```ts
import VueShip from 'vue-snip'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(VueShip);
});
```
I use it like this
```html
<span v-ship="{lines: 2}">My long text</span
```
But I get an error
`[Vue warn]: Failed to resolve directive: ship`

VueJS: 3.3.4
Nuxt: 3.5.3
VueShip: 2.0.1

**Comment by ajobi** [comment]
Hi @masterWeber! It seems like you have a typo, the directive name is `v-snip` instead of `v-ship`.

**Comment by masterWeber** [comment]
@ajobi Oh, I'm sorry I bothered you.

**Comment by ajobi** [comment]
@masterWeber no worries! 😇
